[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn api.main:app --host 0.0.0.0 --port $PORT"

[env]
PYTHONPATH = "/app"

# Runtime settings
[nixpacks.phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[nixpacks.phases.install]
cmds = ["pip install -r requirements.txt"]

[nixpacks.phases.build]
cmds = []

# Health check configuration
[healthcheck]
path = "/api/health"
